export const animations = [
    {
        id: 0,
        name: 'Workspace',
        description: 'Animation window to run and test the code.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/@workspace',
        isEnabled: true,
    },
    {
        id: 1,
        name: 'Rotating Cube',
        description: 'Simple cube spinning on its axis.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/cube.animation.tumbnail.image.png',
        animationPageURL: '/animations/rotating.cube',
        isEnabled: true,
    },
    {
        id: 2,
        name: 'Solar System',
        description: 'Animations of planets rotating around the sun.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/solar.system.animation.tumbnail.image.png',
        animationPageURL: '/animations/solar.system',
        isEnabled: true,
    },
    {
        id: 3,
        name: 'Binary Star System',
        description: 'Simulation of a binary star system',
        lastUpdatedDate: '21 April, 2025',
        displayImageURL: '/images/bstar.system.animation.tumbnail.image.png',
        animationPageURL: '/animations/binary.star.system',
        isEnabled: true,
    },
    {
        id: 4,
        name: 'Fourier Epicycles',
        description: 'Rotating circles which can draw any shape.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/fourier.epicycles',
        isEnabled: false,
    },
];