export const animations = [
    {
        id: 0,
        name: 'Workspace',
        description: 'Animation window to run and test the code.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/@workspace',
        isEnabled: true,
    },
    {
        id: 1,
        name: 'Rotating Cube',
        description: 'Simple cube spinning on its axis.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/cube.animation.tumbnail.image.png',
        animationPageURL: '/animations/rotating.cube',
        isEnabled: true,
    },
    {
        id: 2,
        name: 'Solar System',
        description: 'Animations of planets rotating around the sun.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/solar.system.animation.tumbnail.image.png',
        animationPageURL: '/animations/solar.system',
        isEnabled: true,
    },
    {
        id: 3,
        name: 'Binary Star System',
        description: 'Simulation of a binary star system',
        lastUpdatedDate: '21 April, 2025',
        displayImageURL: '/images/bstar.system.animation.tumbnail.image.png',
        animationPageURL: '/animations/binary.star.system',
        isEnabled: true,
    },
    {
        id: 4,
        name: 'Colliding Balls',
        description: 'Balls collision simulation with controlled parameters',
        lastUpdatedDate: '21 April, 2025',
        displayImageURL: '/images/colliding.balls.animation.tumbnail.image.png',
        animationPageURL: '/animations/colliding.balls',
        isEnabled: true,
    },
    {
        id: 5,
        name: 'Mandelbrot Zoom',
        description: 'Mandelbrot Zoom',
        lastUpdatedDate: '22 April, 2025',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/mandelbrot.zoom',
        isEnabled: true,
    },
    {
        id: 6,
        name: 'Prime Wave',
        description: 'Prime Wave',
        lastUpdatedDate: '24 April, 2025',
        displayImageURL: '/images/prime.wave.animation.tumbnail.image.png',
        animationPageURL: '/animations/prime.wave',
        isEnabled: true,
    },
    {
        id: 7,
        name: 'Fourier Epicycles',
        description: 'Rotating circles which can draw any shape.',
        lastUpdatedDate: '20 April, 2025',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/fourier.epicycles',
        isEnabled: true,
    },
    {
        id: 8,
        name: 'Double Pendulum',
        description: 'Choas Simulation of Multiple Double Pendulum',
        lastUpdatedDate: '30 April, 2025',
        displayImageURL: '/images/dpendulums.animation.tumbnail.image.png',
        animationPageURL: '/animations/double.pendulam',
        isEnabled: true,
    },
    {
        id: 9,
        name: "Conway's Game of Life",
        description: "Conway's Game of Life",
        lastUpdatedDate: '1 May, 2025',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/game.of.life',
        isEnabled: true,
    },
];