export const animations = [
    {
        id: 0,
        name: 'Workspace',
        description: 'Animation window to run and test the code.',
        version: 'v1.0.0',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/@workspace',
        isEnabled : true,
    },
    {
        id: 1,
        name: 'Rotating Cube',
        description: 'Simple cube spinning on its axis.',
        version: 'v1.0.0',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/cube',
        isEnabled : true,
    },
    {
        id: 2,
        name: 'Solar System',
        description: 'Animations of planets rotating around the sun.',
        version: 'v1.0.0',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/solar.system',
        isEnabled : true,
    },
    {
        id: 3,
        name: 'Fourier Epicycles',
        description: 'Rotating circles which can draw any shape.',
        version: 'v1.0.0',
        displayImageURL: '/images/@default.animation.tumbnail.image.jpg',
        animationPageURL: '/animations/fourier.epicycles',
        isEnabled : true,
    },
];